### ISSUE TITLE
Expected format for date fields

### ISSUE THREAD

**Issue by jenskutilek** [typeWorld/guiapp#5]
I’m trying to connect the gui app to my own API server. When I give e.g. the version.releaseDate as string, as per the specification, the gui app returns an error when I try to add the publisher: `ValueError: invalid literal for float(): 2018-10-05`

My version json:

```json
"versions": [
  {
    "number": "1.7",
    "releaseDate": "2018-10-05"
  }
]
```

**Comment by yanone** [comment]
Yes, I recently changed some fields in the specs from timestamp integers to date strings to avoid time zone issues, but the 0.1.2 version that's out doesn't know about them yet. 
These changes might continue to happen until the protocol is declared final. I'll see if I can keep a changelog in the future.

I'll be traveling for a couple of days. In about a week I'll publish 0.1.3 for Mac and Windows, which will know about the changes.

**Comment by jenskutilek** [comment]
It could be helpful if the error message in the app also contained the name of the field which threw the error, in this case "releaseDate".
